### ISSUE TITLE
Submit to Package Control

### ISSUE THREAD

**Issue by nunofgs** [voronianski/oceanic-next-theme#1]
Looks great. How about submitting this to Package Control? :)

**Comment by voronianski** [comment]
@nunofgs thanks! I will do it today :soon:

**Comment by tinchoz49** [comment]
niceee theme!!! yess please, submit to Package Control!

**Comment by mdaverde** [comment]
+1

**Comment by voronianski** [comment]
@nunofgs @tinchoz49 @milanlandaverde 

It's now available on [Package Control](https://packagecontrol.io/packages/Oceanic%20Next%20Color%20Scheme).
