### ISSUE TITLE
Vim Port?

### ISSUE THREAD

**Issue by adamalbrecht** [voronianski/oceanic-next-theme#10]
Really fantastic theme. Would love to see a Vim port if someone is up to it.

**Comment by jeffpamer** [comment]
I'll add my support in for this idea, I'd love to see a vim port.

**Comment by yosiat** [comment]
Hi,
I created a port (using coloration and Vim-toCterm) - https://github.com/yosiat/oceanic-next-vim

**Comment by voronianski** [comment]
@yosiat kudos! :+1: :fireworks:
