### ISSUE TITLE
Color pallet 

### ISSUE THREAD

**Issue by mhartington** [voronianski/oceanic-next-theme#14]
Similar to http://chriskempson.github.io/base16/#ocean

![](https://camo.githubusercontent.com/e265d55a7795c2f3c504842cc7b4e5e67e4db64f/68747470733a2f2f7261772e6769746875622e636f6d2f63687269736b656d70736f6e2f6261736531362f6d61737465722f6261736531362d64656661756c742e706e67)

I would be useful for generating new themes to have a set list of colors that we can work with.

**Comment by mhartington** [comment]
went a head and threw one together
![base16-oceanic-next](https://cloud.githubusercontent.com/assets/2835826/8026507/02a7247e-0d47-11e5-8d9f-2781dcfb9223.png)

If you have any feed back on any of the color or find that some are a little off (used photoshop and the color picker) feel free to let me know what should be changed.

base00: "1a2b34"
base01: "343d46"
base02: "4f5b66"
base03: "65737e"
base04: "a7adba"
base05: "c0c5ce"
base06: "dfe1e8"
base07: "cdd3de"
base08: "ee5d64"
base09: "fb9150"
base0A: "fbc959"
base0B: "98c892"
base0C: "5ab3b4"
base0D: "6498ce"
base0E: "c693c6"
base0F: "ab7967"

**Comment by voronianski** [comment]
@mhartington thanks! I've updated your list a bit and added to README - https://github.com/voronianski/oceanic-next-theme#color-palette

**Comment by mhartington** [comment]
Sweet, I think with this, now I could work on the iterm 2 theme :smile:
