### ISSUE TITLE
Light implementation?

### ISSUE THREAD

**Issue by mhartington** [voronianski/oceanic-next-theme#18]
Could be useful for people who like light colour-schems. Thoughts?

**Comment by stephenhowells** [comment]
I'd do this but I've never made or edited a color scheme. I don't even know where to begin. Having said that a light version would be awesome. At some point if it's not community contributed I'll get on it.

**Comment by ghost** [comment]
You can try to use [Otto Yesterday](https://github.com/oivva/otto). Colorscheme template is based on **Oceanic Next Color Scheme** but with colors of [Base16 Yesterday Light](https://github.com/chriskempson/base16-builder)

**Comment by voronianski** [comment]
@oivva looks nice :+1: 

btw @stephenhowells @mhartington I'm considering to start light theme implementation soon.

**Comment by mhartington** [comment]
@voronianski nice! I've been messing around a bit with the vim/neovim implementation of a light theme as well.

Still needs a lot of work, at least to make the contrast better ( it would be nice to actually be able to see what I'm typing heh)

<img width="1680" alt="screen shot 2016-03-11 at 7 10 29 am" src="https://cloud.githubusercontent.com/assets/2835826/13701922/0a58fcf0-e759-11e5-92de-0ac0bc64e54f.png">
