### ISSUE TITLE
base16 port created

### ISSUE THREAD

**Issue by wbinnssmith** [voronianski/oceanic-next-theme#19]
Hey @voronianski,

Love the color scheme! I ended up creating [a small gnu make build](https://github.com/wbinnssmith/base16-oceanic-next) that uses the base16-builder to output configurations for all of the editors supported there. It ended up making a very nice scheme for where I'm using it (vim), but there are a few drawbacks:
- We're limited to highlighting js language features to the extent that base16 itself supports them.
- Really only the dark color scheme (not the light) works well, and it seems light is the default, at least for the vim build. Good thing the dark one looks incredible :)

I'm not sure there's much to do re: the light scheme, or if that's something that's crossed your mind, or if it's worth supporting. As for esnext support, I'll see if I can get changes into base16 to make that happen (at least on vim, where [there are alternative](https://github.com/pangloss/vim-javascript) syntax definitions for js just like babel-sublime).

Thanks again. Wondering what your thoughts are!

**Comment by voronianski** [comment]
@wbinnssmith thanks, regarding your input:

> the light scheme

For now I don't feel inspiration for creating the light version however I may change my mind soon. If there will be some help I'll appreciate it.

> As for esnext support, I'll see if I can get changes into base16 to make that happen (at least on vim, where there are alternative syntax definitions for js just like babel-sublime)

This sounds huge :+1: btw I wonder does vim has some sort of packages to add support of ES6/ES7 features + JSX?

**Comment by mhartington** [comment]
Hey just wanted to chime in on this....

I used base16 as well for a base in creating a vim port as well.
https://github.com/mhartington/oceanic-next

Slightly tweaking the colors here and there for true color and 256 color support.
For ES6 support in vim, I use 

 [vim-javascript](https://github.com/pangloss/vim-javascript)

 [vim-jsx](https://github.com/mxw/vim-jsx)

And I get pretty good syntax highlighting compared to sublime text.

As far as light theme goes, I'm sure there could be some small tweaks here and there, currently working on that myself, and hope to contribute it back to the main theme.
