### ISSUE TITLE
Suggest good companion themes in README

### ISSUE THREAD

**Issue by nunofgs** [voronianski/oceanic-next-theme#2]
I was using Spacegray but I find that the background color isn't a good fit with Oceanic Next:

![screen shot 2015-02-09 at 12 51 29](https://cloud.githubusercontent.com/assets/92085/6106614/ccc8dde6-b05a-11e4-8570-70cd04d685fc.png)

Out of curiosity, what Sublime theme are you using? 

Also, could this be something that other people find interesting? maybe add a small list to the README of good-looking themes that fit with the overall style of Oceanic Next?

**Comment by voronianski** [comment]
@nunofgs I'm using it with [El Capitan Sublime Theme](https://github.com/iccir/El-Capitan-Theme).

As for me I'm not aware of Sublime Themes, I've used Spacegray for a long time but recently I found myself that contrast with more classy Mac OS X white feel is just great :smile: 

![](https://dl.dropboxusercontent.com/u/100463011/el-capitan-with-oceanic-next.png)

I can just suggest to google smth similar to - https://scotch.io/bar-talk/the-best-sublime-text-3-themes-of-2014

**Comment by mertkahyaoglu** [comment]
I agree :+1: and which font are you using ?

**Comment by jenbennings** [comment]
I am currently using the same setup as @nunofgs — it bothered me enough to modify the colours of the Spacegray theme. I'm going to try and implement them later today. Here's a before/after preview:

![](http://cl.ly/image/2M3R392L130K/Screen%20Shot%202015-02-21%20at%2012.22.41%20PM.png)

Not a huge change—but it's the little things, right?

**Comment by voronianski** [comment]
@mertkahyaoglu http://www.levien.com/type/myfonts/inconsolata.html

**Comment by jenbennings** [comment]
Spent half an hour or on it yesterday:

![](http://cl.ly/image/12230b2e0Z12/Screen%20Shot%202015-02-22%20at%203.24.22%20PM.png)

I've also changed the unsaved & close icon tints to match the same red/yellow :sunglasses: — if anyone wants it I can gist the theme file.

**Comment by voronianski** [comment]
@jenbennings hey, this looks pretty, share the theme file please :+1:

**Comment by nunofgs** [comment]
Yup, looks awesome. Share that thing asap! :+1:

**Comment by jenbennings** [comment]
https://gist.github.com/jenbennings/01022cb691c928f5338a
https://gist.github.com/jenbennings/f4b5e732436810d460ff

**Comment by gaearon** [comment]
:+1:

**Comment by WickyNilliams** [comment]
I was just about to raise an issue about adding a theme, and planned to look at it tonight. Awesome that @jenbennings beat me to it!

What are the chances of getting this added to the repo as the official compliment to the colour scheme?

**Comment by voronianski** [comment]
@WickyNilliams maybe just a line in README? :smile:

**Comment by WickyNilliams** [comment]
@voronianski but why not include in an official capacity? It would be opt-in (you have to go into your sublime settings and explicitly change the theme), so users who just want the colour theme get only that. 

It works beautifully. And it would be good to have something that's not floating about in a gist somewhere, that can be improved/fixed over time.

**Comment by gaearon** [comment]
+1 to @WickyNilliams

**Comment by voronianski** [comment]
@WickyNilliams @gaearon alright you win! so you just want me to include those files by @jenbennings ?

**Comment by WickyNilliams** [comment]
The power of peer pressure :smile: 

The sublime-theme file can just be added to root of repo, along with instructions in README on how to set it (see how [spacegray theme describes the process](https://github.com/kkga/spacegray#how-to-activate)). It boils down to adding the following lines to your user settings:

``` json
"color_scheme": "Packages/Oceanic Next Color Scheme/Oceanic Next.tmTheme",
"theme": "Spacegray Ocean.sublime-theme",
```

As for the `Widget - Spacegray.stTheme` file, i'm not entirely sure what you're supposed to do with that to get it to work... I had to modify my `Packages/Theme - Default/Widget.sublime-settings` to point to that file:

``` json
{
  "color_scheme": "Packages/Oceanic Next Color Scheme/Widgets.stTheme"
}
```

But I know that's not the right thing to do, as I've never done it with other themes. Can't find relevant sublime documentation on how to get it to work. Maybe @jenbennings is best placed to answer that part.

**Comment by jenbennings** [comment]
@WickyNilliams From memory, I only modified the widget file to change the color of the search prompt (this isn't set as part of the .stTheme).

Perhaps I should set it up as a fork of spacegray so it can be installed as part of package control. It would be a good process to figure out how Sublime Text themes actually work, however it won't be a quick process! For now I was happy with modifying spacegray manually.

**Comment by sebastienbarre** [comment]
Nice job @jenbennings! I installed `Spacegray Ocean.sublime-theme` and it works beautifully, although you need to install the [spacegray](https://github.com/kkga/spacegray) theme first, since your theme makes explicit references to its bitmaps (say, `"layer0.texture": "Theme - Spacegray/Spacegray/close.png"`). A fork of `spacegray` would be great!

**Comment by bjankord** [comment]
I've been using the Spacegray Eighties theme:
`"theme": "Spacegray Eighties.sublime-theme"`

![sublime](https://cloud.githubusercontent.com/assets/633148/6926533/7ae1edd2-d7ac-11e4-9605-9d3533797084.png)

The theme @jenbennings came up with looks awesome, going to try it out now.

**Comment by voronianski** [comment]
@jenbennings hey, so did you manage to make a fork of `Spacegray` ➫ `Spacegray Ocean`? If no, probably I can do it, just clearifying :smile:

**Comment by jenbennings** [comment]
@voronianski Sorry, haven't had a chance to do it yet! Feel free to use my files if you'd like to do it yourself.

**Comment by WickyNilliams** [comment]
Personally, I think it would be nice to have Spacegrey forked/merged into this repo along with @jenbennings' changes, rather than a new repo. As a user, it would be far more convenient to have a single package.

**Comment by WickyNilliams** [comment]
Also worth noting I've been using them together, as described above, for quite some time, with zero issues

**Comment by emadb** [comment]
I tried to create a better theme for oceanic next. I started from Seti_UI.

The result is this:
![screenshot 2015-04-20 16 40 34](https://cloud.githubusercontent.com/assets/276876/7232518/5797edf6-e77c-11e4-8bc1-d7e74a3e64ba.png)

And the config file is here: https://gist.github.com/emadb/2f4b3137f0345248a8a2

It's not finished and it should be packaged in a real UI theme. Feel free to go on  from here :-)

**Comment by charliecm** [comment]
@WickyNilliams I found that you can put the `Widget - Spacegray Ocean.sublime-settings` file anywhere outside of `Packages/User` and it'll work.

@jenbennings Thanks for making the mods. Now I can code sanely :wink:

**Comment by WickyNilliams** [comment]
This seriously broke things when this theme recently updated. Resulted in all the custom additions going missing, causing Sublime to get very confused. 

@voronianski are you still open to having these added to the repo?

**Comment by voronianski** [comment]
@WickyNilliams I'm open to add it.

**Comment by WickyNilliams** [comment]
Can anyone point me to relevant sublime docs for creating a custom theme (assuming they exist!)? Most parts can be added straight to the repo, and are fairly easy to integrate. But I'm still stuck as to how to get the Widgets.stTheme integrated correctly

**Comment by ericmatthys** [comment]
https://github.com/ericmatthys/spacegray-oceanic-next

I forked Spacegray to better fit Oceanic Next.

**Comment by voronianski** [comment]
@ericmatthys :+1:

**Comment by tomv564** [comment]
I forked the Afterglow theme and adjusted the blue version:

<img width="1021" alt="screen shot 2015-09-20 at 23 16 29" src="https://cloud.githubusercontent.com/assets/4395832/10041003/2e7e8d14-61e1-11e5-9c94-692d8c8f1b1b.png">

See https://github.com/tomv564/oceanic-afterglow for installation.

**Comment by jakech** [comment]
@ericmatthys thanks, but i cant find it on package control. :(

**Comment by ericmatthys** [comment]
@jakech I haven't added it to package control yet. You'd need to install it manually.

**Comment by jakech** [comment]
@ericmatthys thats cool, thanks a lot

**Comment by edheltzel** [comment]
I use [Material Theme](http://equinusocio.github.io/material-theme/) by @equinusocio
Looks pretty good with **Oceanic Next**
![ Material Theme](http://rdm.d.pr/18lhw+)

**Comment by ritz078** [comment]
**Theme** - Soda Dark
**Font** - Monaco
**Result** - Awesome :smile: 

<img width="1440" alt="screen shot 2015-10-26 at 1 31 45 am" src="https://cloud.githubusercontent.com/assets/5389035/10717541/92d29ab2-7b81-11e5-9b90-c390a1894944.png">

**Comment by ericmatthys** [comment]
@voronianski It looks like that requires Spacegray to be installed separately, which isn't mentioned in the README. Without Spacegray, the theme has no images.

**Comment by WickyNilliams** [comment]
@ericmatthys oops, that's an oversight on my part. Will fix this evening

**Comment by WickyNilliams** [comment]
@ericmatthys made a PR to fix this: #27

**Comment by WickyNilliams** [comment]
Can anyone confirm the new theme is working for them? Uninstalled all my themes, then installed Oceanic and it seems good to me. @ericmatthys

**Comment by ericmatthys** [comment]
@WickyNilliams :+1: seems ok here

**Comment by WickyNilliams** [comment]
Great! Good to know :)

**Comment by equinusocio** [comment]
Material Theme will be provided with the original Oceanic Next (only bg and comments changed).

**Comment by edheltzel** [comment]
Looks pretty good ... one less Sublime Package to install

**Comment by equinusocio** [comment]
Yes, but you will have to activate it. Check the README file.

**Comment by edheltzel** [comment]
@equinusocio Since I already used that color scheme I have it under my user settings for my package configuration so for me -- personally its on less dependency. I should note I use SublimeLinter and ColorHighlighter.

**Comment by arvi** [comment]
I created a theme early this year wherein the default, origin, and classic theme are based on Oceanic Next since I'm a fan haha. Thanks for your great work. :)

https://github.com/arvi/Agila-Theme
