### ISSUE TITLE
Has the Syntax Highlighting Changed?

### ISSUE THREAD

**Issue by cameronbourke** [voronianski/oceanic-next-theme#26]
Just installed this killer theme, especially when working with ES6. However, when I look at the JSX in sublime that I've got:
http://puu.sh/l2LW6/bd1fb04691.png

It doesn't match up to the JSX on the Github page for this repo, http://labs.voronianski.com/oceanic-next-color-scheme/. Screenshot also is here:
http://puu.sh/l2M8v/5d839985c7.png

**Comment by voronianski** [comment]
@cameronbourke it was a bug in babel-sublime package. It's already fixed via - https://github.com/babel/babel-sublime/pull/206
