### ISSUE TITLE
Theme on Linux doesn't work properly

### ISSUE THREAD

**Issue by Oxyrus** [voronianski/oceanic-next-theme#28]
Trying with

```
"color_scheme": "Packages/Oceanic Next Color Scheme/Oceanic Next.tmTheme",
"theme": "Oceanic Next.sublime-theme"
```

![http://i.imgur.com/trQztlE.png](http://i.imgur.com/trQztlE.png)

Already restarted the editor, but it doesn't look good.

**Comment by voronianski** [comment]
@Oxyrus could you share screenshot of what exactly looks no good?

**Comment by Oxyrus** [comment]
@voronianski the sidebar, no icons, only text, the margins on directories are somewhat buggy, or is it intended to look and work like that?

**Comment by Dajust** [comment]
@voronianski Also, we have only one color scheme - Oceanic Next. How do we add all other color palette you talked about?

**Comment by voronianski** [comment]
@Oxyrus is it still actual? maybe you have another Sublime packages that break it.

**Comment by voronianski** [comment]
@Dajust Sorry, didn't understand your question.

**Comment by Oxyrus** [comment]
@voronianski I not longer use Sublime so I don't know :stuck_out_tongue_winking_eye:
