### ISSUE TITLE
let not treated like var

### ISSUE THREAD

**Issue by raybooysen** [voronianski/oceanic-next-theme#29]
As per the screenshot, let is not treated with the same colour as var.
![image](https://cloud.githubusercontent.com/assets/461957/11370502/febdec8a-92bb-11e5-941c-c1bce234f23a.png)

**Comment by voronianski** [comment]
@raybooysen that's strange, we have it fine on our machines, what is the version of [babel-sublime](https://github.com/acdlite/flummox/issues) package on your machine?

**Comment by raybooysen** [comment]
v8.6.2

**Comment by voronianski** [comment]
And what version of Oceanic Next and your OS? I cannot reproduce this on Mac OS X and Windows for now.

**Comment by raybooysen** [comment]
Using Windows 10
Oceanic Next = 0.1.8

**Comment by flekschas** [comment]
Same here on Mac OS X `v10.10`. I am also using OceanNext `v0.1.8` and Babel-sublime `v8.6.2`.

**Comment by ianwith** [comment]
+1

**Comment by voronianski** [comment]
Do you, guys, still have this issue?

**Comment by ryanzec** [comment]
Works fine for me.

OS X: 10.11.3
Babel Sublime: 8.6.3
Ocean Next: 0.1.11

**Comment by voronianski** [comment]
I'm closing it for now :)
