### ISSUE TITLE
JSON keys and values

### ISSUE THREAD

**Issue by victorwpbastos** [voronianski/oceanic-next-theme#30]
Would be great to have some different colors for `keys` and `values`in JSON documents. 

Actually:

![image](https://cloud.githubusercontent.com/assets/1017515/11414591/4dc815b2-93de-11e5-9536-73c2b99abf74.png)

Monokai Neue [https://github.com/josh-kaplan/sublime-monokai-neue]:

![image](https://cloud.githubusercontent.com/assets/1017515/11414600/6e05cfcc-93de-11e5-9273-56ff2cc7816f.png)

**Comment by incleaf** [comment]
:+1:

**Comment by voronianski** [comment]
@victorwpbastos @incleaf added in `0.1.11`.
