### ISSUE TITLE
Certain object properties are colored orange, most are white and some are blue

### ISSUE THREAD

**Issue by flekschas** [voronianski/oceanic-next-theme#31]
I notice that object properties seem to be colored randomly at times. While most of the times they are white, sometimes properties are colored blue (e.g. _select_) and some are orange (e.g. _data_, _width_ or _domain_). Is this intended? 

![rainbow](https://cloud.githubusercontent.com/assets/932103/11535722/1319b6e6-98e3-11e5-95f1-ec3ef84b9bd6.jpg)

I am using Sublime Text 3, OceanNext `v0.1.8` and Mac OS X 10.10

**Comment by voronianski** [comment]
@flekschas never experienced such behavior.. are you sure that all is setup properly? Maybe you can share the whole file content?

**Comment by flekschas** [comment]
Sorry it seemed to have been an issue with Sublime Text 3. I copy and pasted the same code that looked broken into a new file and everything was just fine. Note sure how this happened. Sorry for the hassle :)
