### ISSUE TITLE
Semicolons required for some syntax coloring

### ISSUE THREAD

**Issue by ziemkowski** [voronianski/oceanic-next-theme#33]
With the growing movement of avoiding unnecessary and subjectively ugly semicolons in ES6+, especially when using new features, it would be nice if oceanic-next supported it better.

Current coloring without semicolons:
![screenshot](http://chat-files.tave.com/screenshot.20160106.1247.su99o.png)
with semicolons:
![screenshot](http://chat-files.tave.com/screenshot.20160106.1249.up0yk.png)

Example code is from http://babeljs.io/blog/2015/06/07/react-on-es6-plus/#property-initializers

``` js
// The ES6+ way
class Video extends React.Component {
  static defaultProps = {
    autoPlay: false,
    maxLoops: 10,
  }
  static propTypes = {
    autoPlay: React.PropTypes.bool.isRequired,
    maxLoops: React.PropTypes.number.isRequired,
    posterFrameSrc: React.PropTypes.string.isRequired,
    videoSrc: React.PropTypes.string.isRequired,
  }
  state = {
    loopsRemaining: this.props.maxLoops,
  }
}
```

In large class files this can lead to all kinds of strange colorings.

**Comment by jptissot** [comment]
This seems to happen with all color schemes. Probably not related to this one specifically.

**Comment by svipas** [comment]
This happens I guess only in ST. I checked and everything is alright with VS Code.

**Comment by voronianski** [comment]
This is sublime color schemes scopes issue, related to all schemes unfortunately. Nothing we can do about it here.
