### ISSUE TITLE
Color scheme not displayed when have more than fifteen levels of {}

### ISSUE THREAD

**Issue by fabriciosomini** [voronianski/oceanic-next-theme#36]
Hello, I hope I'm posting the issue on the right repo.

When the user uses more than 15 inner {} the color synthax will stop.
Verify the image for details.
![bug](https://cloud.githubusercontent.com/assets/15656090/13463548/7f5cea74-e06b-11e5-99f8-6dcbb97958e3.jpg)

Environment: Sublime 3
Language: Javascript
Theme: Material Theme (Material Theme-Oceanic Next)
Linter: JSHint

**Comment by voronianski** [comment]
@fabriciosomini it looks like an issue with babel-sublime. I've create an issue there as well - https://github.com/babel/babel-sublime/issues/249

**Comment by svipas** [comment]
Seems this issue was fixed so I guess it can be closed here too.
