### ISSUE TITLE
provide user preferences string for installation

### ISSUE THREAD

**Issue by venil7** [voronianski/oceanic-next-theme#4]
please provide user preferences string, so that people can copy and paste it into their preferences, after install

eg. `"color_scheme": "Packages/Oceanic Next Color Scheme/Oceanic Next.tmTheme",`

**Comment by voronianski** [comment]
@venil7 please use Package Control to install.

**Comment by voronianski** [comment]
@venil7

**Comment by venil7** [comment]
using Package Control doesn't automatically change the scheme for a user, at least it didn't for me, they still need to activate it in their preferences, and copying this line - is the quickest way of doing that...

**Comment by venil7** [comment]
i meant, if you add this to README, it would save some time for people installing it

**Comment by voronianski** [comment]
@venil7 this line depends on user preferences and packages, the quickest way is to use Sublime's menu.
