### ISSUE TITLE
somethings up with my highlighting...

### ISSUE THREAD

**Issue by export-mike** [voronianski/oceanic-next-theme#40]
I've got: 

babel sublime installed, v8.6.3
oceanic-next-color-scheme installed v0.1.11
sublime 3 latest (3103)

user settings: 

``` json

{
    "color_scheme": "Packages/User/SublimeLinter/Oceanic Next (SL).tmTheme",
    "font_face": "Hack",
    "font_size": 14,
    "ignored_packages":
    [
        "Vintage"
    ],
    "tab_size": 2,
    "theme": "Oceanic Next.sublime-theme",
    "translate_tabs_to_spaces": true
}
```

and it looks like this :( 
![image](https://cloud.githubusercontent.com/assets/2983327/14139907/e6b79c42-f66d-11e5-9358-44bc4823605e.png)
any ideas?

**Comment by voronianski** [comment]
@export-mike that's crazy.. never encountered smth like this. Are you on Mac? Maybe you have additional packages that can conflict with babel-sublime?

**Comment by export-mike** [comment]
possibly... here's my list.. is there a way to get a list of all packages and versions? 
![image](https://cloud.githubusercontent.com/assets/2983327/14140546/886794a4-f671-11e5-8614-7edbb8f6bc0a.png)

**Comment by voronianski** [comment]
@export-mike Package Control -> List Packages

**Comment by voronianski** [comment]
Maybe Numix?

**Comment by ikanievska** [comment]
@export-mike any updates?

**Comment by export-mike** [comment]
I reinstalled everything working fine now, thanks for your help

**Comment by olegakbarov** [comment]
Got the same issue. Interestingly enough it appears in the same place — after destructuring:

``` js
<DoorHeader {...this.props} />
```

Reinstall doesn't help so far.

**Comment by export-mike** [comment]
Yeah I've since switched to atom. So far its a great experience

**Comment by olegakbarov** [comment]
@export-mike you got this issue again after reinstall? 😭

**Comment by export-mike** [comment]
Yeah my bad, I thought everything was OK but turns out it wasn't, sorry I never updated the issue

**Comment by olegakbarov** [comment]
I'd be grateful for any ideas on this. Atom way too slow for me.

**Comment by export-mike** [comment]
When was the last time you tried it? I've been using the nuclide plugins
and babel plugins with has millions of downloads. I did find it to be slow
on an old macbook pro 2009

**Comment by olegakbarov** [comment]
@export-mike  Last summer i belive, quite a while ago.

By the way seems like this is a [Babel-Sublime issue](https://github.com/babel/babel-sublime/issues/250)

**Comment by olegakbarov** [comment]
@export-mike This helped me:

In sublime:
Syntax -> Open all with current extension as... -> Babel -> JavaScript (Babel)

**Comment by voronianski** [comment]
@olegakbarov good point, probably this should be added to README.

**Comment by olegakbarov** [comment]
@voronianski PR? 😉

**Comment by RegisBiron** [comment]
I'm still having syntax highlighting issues even after reinstalling ST 3, deleting all packages, reinstalling etc, clearing caches. My theme was perfect before I upgraded to stable 3114. 

These issues didn't exist in the previous stable build...

## SASS 
![screen shot 2016-05-19 at 3 00 45 pm](https://cloud.githubusercontent.com/assets/8062034/15406039/a94b0f24-1dd2-11e6-85bd-eebee9b5744c.png)

## PostCSS using syntax highlighting for PostCSS package
![screen shot 2016-05-19 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/8062034/15406128/1508256c-1dd3-11e6-8f04-13e47e255321.png)

### $ used in PHP and JS variables 
![screen shot 2016-05-19 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/8062034/15406081/e5823d6e-1dd2-11e6-883a-8a6b6a3621ce.png)

**Comment by JimLin94** [comment]
@olegakbarov Thanks man. You save my day.
