### ISSUE TITLE
Suggestion: Make object properties different color form strings

### ISSUE THREAD

**Issue by ryanzec** [voronianski/oceanic-next-theme#41]
This is what a JSON object looks like by default:

<img width="179" alt="screen shot 2016-04-07 at 7 45 09 pm" src="https://cloud.githubusercontent.com/assets/444206/14370188/806d03ea-fcf9-11e5-9767-1614030c3d1a.png">

So I took a look at the .tmTheme file can changed this:

```
<dict>
    <key>name</key>
    <string>String, Symbols, Inherited Class, Markup Heading</string>
    <key>scope</key>
    <string>string, constant.other.symbol, constant.other.key, entity.other.inherited-class, markup.heading, markup.inserted.git_gutter, meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>normal</string>
        <key>foreground</key>
        <string>#99C794</string>
    </dict>
</dict>
```

to this:

```
<dict>
    <key>name</key>
    <string>String, Symbols, Inherited Class, Markup Heading</string>
    <key>scope</key>
    <string>string, constant.other.symbol, constant.other.key, entity.other.inherited-class, markup.heading, markup.inserted.git_gutter</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>normal</string>
        <key>foreground</key>
        <string>#99C794</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>String, Inherited Class, Markup Heading</string>
    <key>scope</key>
    <string>meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>normal</string>
        <key>foreground</key>
        <string>#CDD3DE</string>
    </dict>
</dict>
```

<img width="179" alt="screen shot 2016-04-07 at 7 45 25 pm" src="https://cloud.githubusercontent.com/assets/444206/14370213/f4fe4f34-fcf9-11e5-856c-06594af307a8.png">

The second version seems a lot better to me and a lot more normal.  It just does not make sense for unquoted object properties to be the same color and strings.  A lot of times the value is a string and just seeing a bunch of green looks really weird to me.  Having the color be the same as a regular variable just seem a lot better.

Would this be a welcomed pull request or is this really the intended color scheme?

**Comment by voronianski** [comment]
PR is welcome

**Comment by voronianski** [comment]
fixed
