### ISSUE TITLE
Indent guides and whitespace look different than on project screenshot

### ISSUE THREAD

**Issue by timche** [voronianski/oceanic-next-theme#42]
I don't know why, but they look different. Am I missing something? I have installed this color scheme like in the instructions described.

How it looks like:
![screen shot 2016-05-01 at 15 47 45](https://cloud.githubusercontent.com/assets/8075074/14942137/37eba89c-0fb4-11e6-8cd0-ef58587169a9.png)

How it should look like:
![](https://raw.githubusercontent.com/voronianski/oceanic-next-theme/master/screenshots/jsx-component.png)

**Comment by b4stien** [comment]
I have the same problem, it wasn't the case until very recently (can't pinpoint what have changed in my setup in the last days though...).

**Comment by alexkvazos** [comment]
![screen shot 2017-05-10 at 7 40 53 pm](https://cloud.githubusercontent.com/assets/4448627/25927045/b6f7e5d0-35b8-11e7-8e04-ae0c1bb05f7e.png)
same

**Comment by voronianski** [comment]
fixed

**Comment by timche** [comment]
Although I'm not using ST anymore, thanks for fixing it! :pray:
