### ISSUE TITLE
A definitive guide on colors

### ISSUE THREAD

**Issue by gsklee** [voronianski/oceanic-next-theme#45]
Can we have a sort of definitive guide on which JavaScript syntactic part gets which color, written down in plain text?

I'm currently trying to port the theme to a few HTML-based editors, but their CSS generators all work differently with different naming conventions, it's really tough to know if I get things right or not with just 2 screenshots.

**Comment by gsklee** [comment]
@voronianski Any comment?

**Comment by voronianski** [comment]
@gsklee sorry, the only guide that I can provide right now is theme yaml file - https://github.com/voronianski/oceanic-next-color-scheme/blob/master/Oceanic%20Next.YAML-tmTheme
