### ISSUE TITLE
Suggestion: implement file icons

### ISSUE THREAD

**Issue by JuHwon** [voronianski/oceanic-next-theme#48]
File icons would be very nice.
Maybe with an optional settings flag to enable/disable.

**Comment by voronianski** [comment]
@JuHwon sorry, not sure what you mean.

**Comment by JuHwon** [comment]
@voronianski The theme `"theme": "Oceanic Next.sublime-theme"` does not provide file icons in the sidebar.
Something like that: 
![File Icons](http://imgur.com/1cX2hrwl.png)

**Comment by voronianski** [comment]
@JuHwon actually theme is just an add-on, I though it was fork of some popular theme. We need to ask @WickyNilliams :)
