### ISSUE TITLE
Support styling of static property methods and generator asterix

### ISSUE THREAD

**Issue by tomatau** [voronianski/oceanic-next-theme#5]
Babel sublime has recently updated to support static methods in classes (and hopefully properties for ES7 playground features?)

Would be nice if Oceanic also supported these as it seems to not do just yet.

babel/babel-sublime#52

**Comment by voronianski** [comment]
@tomatau thanks, I will take a look on that.

**Comment by novadev94** [comment]
@tomatau @voronianski Seems like we already have it

![screen shot 2015-03-10 at 11 18 50 pm](https://cloud.githubusercontent.com/assets/6073918/6579321/2d08b4fa-c77c-11e4-90d6-21acae1975f4.png)

**Comment by tomatau** [comment]
This wasn't the case when I posted the issue.

Nice - would be dandy if you could also supported the playground features:
memo methods
static class properties (not methods)
