### ISSUE TITLE
Incompatible VS Code Version

### ISSUE THREAD

**Issue by deniaz** [voronianski/oceanic-next-theme#54]
Hey there

I've tried installing `Oceanic-Next 0.0.1` in `VS Code 1.7.1` and got a `Couldn't find a compatible version of Oceanic-Next with this version of Code.` error. I'm on macOS.

Do I need to ping @mhartington for this? ;)

**Comment by mhartington** [comment]
Thanks for the heads up. I'll take a look at fixing this later today

**Comment by voronianski** [comment]
@deniaz https://github.com/mhartington/vscode-oceanicnext that's the repo for this issue :)
