### ISSUE TITLE
Markdown syntax highlighting issue

### ISSUE THREAD

**Issue by mediter** [voronianski/oceanic-next-theme#58]
First of all, let me just say that Oceanic Next is very pleasant for the eye, quite elegant. I use it for everything including Markdown documents.

However, there is one small issue with list items: if I don't put one extra empty paragraph between the list items, only the first bullet symbol is highlighted.

![oceanic next markdown highlighting issue](https://cloud.githubusercontent.com/assets/57368/21580856/ecc1ad50-d04f-11e6-829b-3acac335db5e.png)

Installed Oceanic Next color scheme as part of [Materialize: Elegant themes for Sublime Text 3](https://github.com/saadq/Materialize)

Sublime Text 3 build 3126 with Markdown Extended as syntax

How can I determine if this issue is arising from the color scheme, the syntax or both?

Thank you very much!

**Comment by voronianski** [comment]
Cannot repro it or it was fixed.

Although I advice to use [Markdown Editing Color Scheme](https://github.com/SublimeText-Markdown/MarkdownEditing) which is great specifically for markdown files. 

This theme is optimized for JavaScript.
