### ISSUE TITLE
Support search results highlighting

### ISSUE THREAD

**Issue by novadev94** [voronianski/oceanic-next-theme#6]
Currently, there's no highlights for the filepath and the result line number:
![screen shot 2015-03-10 at 11 10 40 pm](https://cloud.githubusercontent.com/assets/6073918/6579108/b63c9036-c77a-11e4-9b6e-18df7be01578.png)

How about making it like the default `Monokai` color scheme?
![screen shot 2015-03-10 at 11 11 32 pm](https://cloud.githubusercontent.com/assets/6073918/6579133/d9d46ec4-c77a-11e4-8029-68b002d25463.png)

**Comment by voronianski** [comment]
@NovaDev94 probably I'll take a look on that.

**Comment by bjankord** [comment]
+1, I find myself missing this highlighting from Monokai

**Comment by voronianski** [comment]
@NovaDev94 @bjankord added in `0.1.1`.
