### ISSUE TITLE
Oceanic Next on Photon

### ISSUE THREAD

**Issue by felixsanz** [voronianski/oceanic-next-theme#65]
Hi there! I've added the wonderful Oceanic Next to [photon.sh](https://photon.sh). It's a free syntax highlighter that runs as a service. Your theme is now part of the official collection and it will be updated with regularity. Is this ok?

Here are some examples in case you want to review the correctness or just enjoy it.

- [CSS](https://photon.sh/demo?language=css&theme=oceanic-next)
- [HTML](https://photon.sh/demo?language=html&theme=oceanic-next)
- [Vue.js](https://photon.sh/demo?language=vuejs&theme=oceanic-next)
- [PHP](https://photon.sh/demo?language=php&theme=oceanic-next)
- [Ruby](https://photon.sh/demo?language=ruby&theme=oceanic-next)
- [Go](https://photon.sh/demo?language=go&theme=oceanic-next)

Thanks!

**Comment by felixsanz** [comment]
And by the way i'm using it personally on neovim :stuck_out_tongue_closed_eyes:, so thanks for creating it.

**Comment by voronianski** [comment]
that's awesome! thank you!
