### ISSUE TITLE
Oceanic-next-italic deprecation on Atom

### ISSUE THREAD

**Issue by feruiz** [voronianski/oceanic-next-theme#66]
Hi, sorry if this a know issue, but i read the current issues and i did not found it there.
In Atom (at least 1.18.0 - latest version) appears that oceanic-next-italic has deprecated selectors.

I did a print screen and even i was unable to put all content in the same image and i think it is enough to show the issue.

![capture d ecran 2017-06-21 a 11 43 50](https://user-images.githubusercontent.com/3759595/27390160-ecb9a756-5676-11e7-8b4d-294e4d4e4d6c.png)

Do you want help with this issue?

Thanks a lot for your theme, i love it.

**Comment by voronianski** [comment]
oceanic-next-italic has no relation to this theme, check https://github.com/Bloemert/oceanic-next-italic (maybe it's this one)
