### ISSUE TITLE
Can't find the Oceanic .tmTheme file in SublimeText3 to edit

### ISSUE THREAD

**Issue by leongaban** [voronianski/oceanic-next-theme#67]
https://superuser.com/questions/1224817/cannot-find-the-oceanic-next-tmtheme-to-edit

I've installed the Sublime Text 3 [Oceanic Next.tmTheme][1] and am using it:

[![enter image description here][2]][2]

However unlike all my other Sublime Text 3 themes, I can't find the .tmTheme file to edit it.

ie this file: https://github.com/voronianski/oceanic-next-color-scheme/blob/master/Oceanic%20Next.tmTheme

All I can find on my system is this:

[![enter image description here][3]][3]

Both of which open up a binary file that looks like this:

    504b 0304 1400 0000 0800 b455 944a 338a
	f623 8e00 0000 ca00 0000 0d00 0000 2e65
	6469 746f 7263 6f6e 6669 675d 8e4d 0ac2
	400c 85f7 3945 c19d 600b e242 046f e14e
	4a18 3a99 4e60 9a29 9994 524f 6f2b d685

Where is this theme file installed and how can I edit it?

Just want to add some italics for attributes

  [1]: https://github.com/voronianski/oceanic-next-color-scheme
  [2]: https://i.stack.imgur.com/XZ0VM.png
  [3]: https://i.stack.imgur.com/MXDHE.png

**Comment by justinwager** [comment]
Theme files are not very accessible in ST3, but the following package is useful to edit them.

[PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer)

**Comment by svipas** [comment]
Since this issue is resolved I guess it's time to closed it.
