### ISSUE TITLE
VS Code Oceanic Next theme

### ISSUE THREAD

**Issue by svipas** [voronianski/oceanic-next-theme#69]
Hello, I ported this theme to VS Code, I guess it's time to replace `Mike Hartington` ported theme, because it's out-dated and doesn't have good workbench coloring.

VS Code extension: https://marketplace.visualstudio.com/items?itemName=svipben.oceanic-next-color-theme
GitHub repo: https://github.com/svipben/oceanic-next-color-theme

**Comment by voronianski** [comment]
please create a PR

**Comment by svipas** [comment]
Done https://github.com/voronianski/oceanic-next-color-scheme/pull/70
