### ISSUE TITLE
Quotes and Strings have different colors

### ISSUE THREAD

**Issue by novadev94** [voronianski/oceanic-next-theme#7]
As you can see in this image, the quotes and the strings have different colors:
![screen shot 2015-03-10 at 11 13 19 pm](https://cloud.githubusercontent.com/assets/6073918/6579177/20259d6c-c77b-11e4-97d9-6f25f8fa8fcd.png)

Is this intended or a miscolor?

**Comment by voronianski** [comment]
@NovaDev94 it's by design :)
