### ISSUE TITLE
Plan rewrite using sublime-color-scheme extension ?

### ISSUE THREAD

**Issue by LoiKos** [voronianski/oceanic-next-theme#75]
As the title suggest i would to know if you plan to rewrite a new version or adding a version including the color scheme through a .sublime-color-scheme file ?

**Comment by voronianski** [comment]
@LoiKos do not have such a plan for now, but might take a look into it a bit later.

**Comment by voronianski** [comment]
@LoiKos will close it for now, not sure if there's any profit in changing to `.sublime-color-scheme` as `.tmTheme` works fine.
