### ISSUE TITLE
Theme maintenance

### ISSUE THREAD

**Issue by smhg** [voronianski/oceanic-next-theme#76]
@voronianski can I help maintaining the theme which was removed in 0.2?
Maybe a better first question: why did you decide to remove it?

**Comment by voronianski** [comment]
@smhg I think this repo is not a proper place for UI theme. I want to keep it just for color scheme. I have no interest in supporting UI theme as I never used it actually. Also there was quite amount of issues/bugs in it which was a mess... 

I think if you're interested in maintaining it, the best solution would be to create a separate repo/package for it. We can put a link to it in README here.
