### ISSUE TITLE
iTerm2 Port

### ISSUE THREAD

**Issue by jrodl3r** [voronianski/oceanic-next-theme#8]
Would love this theme in iTerm :+1:

**Comment by mhartington** [comment]
Would love to help out with this. Base16 has a nice builder to let you generate themes for many different editors and terminal shells.

https://github.com/chriskempson/base16-builder

All you would need is a yml file defining the colors like this 
https://github.com/chriskempson/base16-builder/blob/master/schemes/ocean.yml

Again, feel free to reach out, would love to help with this.

**Comment by mhartington** [comment]
Went ahead this weekend and made the iterm2 version, with a light and dark version.
https://github.com/mhartington/oceanic-next-iterm

**Comment by voronianski** [comment]
@mhartington awesome :+1: it will be useful to have screenshots in your README as well.

**Comment by mhartington** [comment]
Good idea, added 

https://github.com/mhartington/oceanic-next-iterm/blob/master/README.md

**Comment by voronianski** [comment]
@mhartington added your implementation to README :+1:
